export * from "./HomePage/HomePage";
export * from "./PrincipalitiesPage/PrincipalitiesPage";
export * from "./PrincipalityPage/PrincipalityPage";
export * from "./LoginPage/LoginPage";
export * from "./RegisterPage/RegisterPage";
export * from "./PopulationDraftPage/PopulationDrafPage"
export * from "./ProfilePage/ProfilePage"
export * from "./PopulationsPage/PopulationsPage"
export * from "./PopulationPage/PopulationPage"